### ISSUE TITLE
DSO curriculum architecture 

### ISSUE THREAD

**Issue by LauraReynal** [chadsansing/curriculum-testing#429]
@chadsansing @secretrobotron 
I see 2 possible architectures, which one do you prefer: 

**Option 1 - Everything is organized by interventions (mix of prototypes and workshops)**
Intervention 1 - curriculum 
Intervention 2 - curriculum
Intervention 3 - Jisort (the game and the content of the tutorials are learning activities) We could make a page that says: "curriculum 3 was delivered on the device directly. download jisort here etc)
Intervention 4 - curriculum
Intervention 5 - TBD software 
Intervention 6 - curriculum

**Option 2 - Everything is organized by workshop only** 
Curriculum 1 
Curriculum 2 
Curriculum 3
Curriculum 4

**Comment by LauraReynal** [comment]
I vote for option 1, because it's the one that is closer to reality, and it's cool to talk about Jisort in the same context as curriculum. It's just another way to teach the web.

**Comment by LauraReynal** [comment]
No matter which one we go for, we should agree on one language 😄 

which one do you prefer ?

**Comment by chadsansing** [comment]
@LauraReynal, typically the modules just have the lesson plans rather than a link to an app or explanation of it. I think we can mention Jisort in Intervention 2 or Intervention 3 and link to it using language like, "Curious to learn more about how to manage smartphone settings and learn about the qweb? Download the Jisort android app here."

As with the project overview, I would recommend a different web page or using the module's landing page to talk about the project in general and about Jisort, specifically, since it is not written as an intervention/lesson plan itself.

**Comment by chadsansing** [comment]
@LauraReynal - anything to add here, or can we close?
